Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,5 +1,3 @@
-name: Deploy to FTP Server
-
 on:
   push:
     branches:
@@ -14,12 +12,32 @@ on:
 
 jobs:
   deploy:
+    name: Deploy
     runs-on: ubuntu-latest
 
     steps:
       # Passo 1: Checkout do código
       - name: 🚚 Get latest code
         uses: actions/checkout@v4
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18'
+
+      - name: 🔨 Install dependencies and build project
+        run: |
+          npm install
+          npm run build
+
+      - name: 🔎 Verify build directory
+        run: |
+          ls -lah
+          if [ ! -d "./build" ]; then
+            echo "❌ Build folder not found! Exiting..."
+            exit 1
+          fi
+          echo "✅ Build folder exists."
 
       # Passo 2: Configurar e realizar o deploy via FTP
       - name: 📂 Upload build files to cPanel via FTP
@@ -45,7 +63,7 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y ftp
-          ftp -inv ${{ secrets.FTP_HOST }} <<EOF
+          ftp -inv ${{ secrets.FTP_SERVER }} <<EOF
           user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
           ls
           bye
